# Basic project configuration
name: pokemonverse
description: "A new Flutter project."
publish_to: 'none'

# Version information
version: 0.0.1

# SDK requirements
environment:
  sdk: ^3.7.2

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  skeletonizer: ^1.4.3
  shared_preferences: ^2.5.3
  


# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
